//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

public partial class Entry9036Entities : DbContext
{
    public Entry9036Entities()
        : base("name=Entry9036Entities")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public virtual DbSet<Bulletin> Bulletins { get; set; }
    public virtual DbSet<Community> Communities { get; set; }
    public virtual DbSet<Message> Messages { get; set; }
    public virtual DbSet<Conference> Conferences { get; set; }
    public virtual DbSet<Department> Departments { get; set; }
    public virtual DbSet<Employee> Employees { get; set; }
    public virtual DbSet<EquipmentRentLog> EquipmentRentLogs { get; set; }
    public virtual DbSet<Equipment> Equipments { get; set; }
    public virtual DbSet<EquipmentType> EquipmentTypes { get; set; }
    public virtual DbSet<Role> Roles { get; set; }
    public virtual DbSet<Customer> Customers { get; set; }
    public virtual DbSet<Evaluation> Evaluations { get; set; }
    public virtual DbSet<Fullevent> Fullevents { get; set; }
    public virtual DbSet<Orderinformation> Orderinformations { get; set; }
    public virtual DbSet<Sale> Sales { get; set; }
}
