//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Bulletin
{
    public int Id { get; set; }
    public string Title { get; set; }
    public Nullable<System.DateTime> Date { get; set; }
    public string Description { get; set; }
    public string Announcer { get; set; }
    public string Department { get; set; }
    public Nullable<int> View { get; set; }
    public string Category { get; set; }
    public Nullable<int> TopPost { get; set; }
    public string FileName { get; set; }
    public string Download { get; set; }
    public string FileUpload { get; set; }
    public string ContentType { get; set; }
    public string Data { get; set; }
}

public partial class Community
{
    public int Id { get; set; }
    public string Name { get; set; }
    public string Content { get; set; }
    public string Datetime { get; set; }
    public Nullable<int> Press { get; set; }
}

public partial class Conference
{
    public int Id { get; set; }
    public string Topic { get; set; }
    public System.DateTime StartTime { get; set; }
    public System.DateTime EndTime { get; set; }
    public System.DateTime CreatedTime { get; set; }
    public string Host { get; set; }
    public string Recorder { get; set; }
    public string Participant { get; set; }
    public string Creator { get; set; }
    public string Content { get; set; }
    public string Application { get; set; }
    public string FileName { get; set; }
}

public partial class Customer
{
    public int CusId { get; set; }
    public string CusName { get; set; }
    public string Phone { get; set; }
    public string Email { get; set; }
    public Nullable<int> SaleID { get; set; }
    public string Development { get; set; }
}

public partial class Department
{
    public int DepartmentID { get; set; }
    public string DepartmentName { get; set; }
}

public partial class Employee
{
    public string EmployeeID { get; set; }
    public string Password { get; set; }
    public Nullable<int> DepartmentID { get; set; }
    public string Position { get; set; }
    public Nullable<int> RoleID { get; set; }
    public string identifier { get; set; }
    public string Name { get; set; }
    public string Gender { get; set; }
    public Nullable<System.DateTime> DateOfBirth { get; set; }
    public string MobilePhoneNumber { get; set; }
    public string ExtensionNumber { get; set; }
    public string Email { get; set; }
    public string Address { get; set; }
    public byte[] ProfilePicture { get; set; }
    public string Introduction { get; set; }
    public Nullable<System.DateTime> DutyDate { get; set; }
    public int State { get; set; }
}

public partial class Equipment
{
    public int EquipmentID { get; set; }
    public string EquipmentName { get; set; }
    public Nullable<int> EquipmentTypeID { get; set; }
    public string EquipmentDescription { get; set; }
    public string EquipmentLife { get; set; }
    public byte[] EquipmentImage { get; set; }
    public int State { get; set; }
    public string Reason { get; set; }
}

public partial class EquipmentRentLog
{
    public int LogsId { get; set; }
    public int EquipmentID { get; set; }
    public System.DateTime StartDate { get; set; }
    public System.DateTime EndDate { get; set; }
    public string EmployeeID { get; set; }
}

public partial class EquipmentType
{
    public int EquipmentTypeID { get; set; }
    public string EquipmentTypeName { get; set; }
}

public partial class Evaluation
{
    public int Id { get; set; }
    public string CusID { get; set; }
    public string Content { get; set; }
    public Nullable<System.DateTime> EvaDate { get; set; }
    public Nullable<int> SaleID { get; set; }
    public string level { get; set; }
}

public partial class Fullevent
{
    public int Id { get; set; }
    public string title { get; set; }
    public System.DateTime start { get; set; }
    public System.DateTime end { get; set; }
    public string color { get; set; }
    public int SaleID { get; set; }
    public string cusName { get; set; }
}

public partial class Message
{
    public int Id { get; set; }
    public string message1 { get; set; }
    public string Name { get; set; }
    public int MId { get; set; }
    public string Datetime { get; set; }
}

public partial class Orderinformation
{
    public int OrderID { get; set; }
    public int OrderAmount { get; set; }
    public System.DateTime OrderDate { get; set; }
    public int SaleID { get; set; }
}

public partial class Role
{
    public int RoleID { get; set; }
    public string RoleName { get; set; }
}

public partial class Sale
{
    public int SaleID { get; set; }
    public string SaleName { get; set; }
    public string Email { get; set; }
}
